In [1]:
import pandas as pd #Alias to the tool that we will be consuming

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
data = pd.read_csv("purchases.csv")

In [4]:
data.head()

  Unnamed: 0  apples  oranges
0       June       3        0
1     Robert       2        3
2       Lily       0        7
3      David       1        2

In [5]:
data = {"Materials": ['Silk','Rose'],
        "Percent": [100,20]}



1.  Series
2.  Data Frame

In [6]:
pandas_data = pd.DataFrame(data)
pandas_data

  Materials  Percent
0      Silk      100
1      Rose       20

In [7]:
type(pandas_data)

pandas.core.frame.DataFrame

In [10]:
type(pandas_data['Materials'])

pandas.core.series.Series

In [12]:
purchases = pd.read_json("purchases.json")

In [13]:
purchases #Columns
#Index

        apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [14]:
data = {"Materials": ['Silk','Rose'],
        "Percent": [100,20]}

pandas_data = pd.DataFrame(data)
pandas_data

  Materials  Percent
0      Silk      100
1      Rose       20

In [15]:
pandas_data = pd.DataFrame(data, index = ["Yes","No"])
pandas_data

    Materials  Percent
Yes      Silk      100
No       Rose       20

In [20]:
data = {"Materials": ['Silk','Rose'],
        "Percent": [100,20],
        "Std": [1,2]}

In [24]:
pandas_data = pd.DataFrame(data, index = ["True","False"])
#index is just an alias to the row as names
pandas_data

      Materials  Percent  Std
True       Silk      100    1
False      Rose       20    2

In [23]:
pandas_data = pd.DataFrame(data)
pandas_data

  Materials  Percent  Std
0      Silk      100    1
1      Rose       20    2

In [18]:
pd.DataFrame?

In [ ]:
#Column - Columns in pandas
#Index - Name given to rows

In [29]:
no_colname = pd.read_csv("purchases_withoutcolums.csv")

In [30]:
no_colname

  Unnamed: 0  Unnamed: 1  Unnamed: 2
0       June           3           0
1     Robert           2           3
2       Lily           0           7
3      David           1           2

In [31]:
no_colname.columns = ['1','2','3']

In [32]:
no_colname

        1  2  3
0    June  3  0
1  Robert  2  3
2    Lily  0  7
3   David  1  2

In [ ]:
#Pyspark - BigData - HeavyDuty Pickup Truck
#Pandas Dataframe - Thar - High performace Cars

In [35]:
!pip install pysqlite3

Collecting pysqlite3
  Downloading pysqlite3-0.6.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Downloading pysqlite3-0.6.0-cp312-cp312-manylinux_2_28_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 43.9 MB/s eta 0:00:00
Installing collected packages: pysqlite3
Successfully installed pysqlite3-0.6.0

In [36]:
import sqlite3

In [37]:
con = sqlite3.connect("database.db")

In [39]:
df = pd.read_sql_query("SELECT * FROM purchases",con)

In [40]:
df

    index  apples  oranges
0    June       3        0
1  Robert       2        3
2    Lily       0        7
3   David       1        2

In [41]:
df.set_index("index")

        apples  oranges
index
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [44]:
df.head(2)

    index  apples  oranges
0    June       3        0
1  Robert       2        3

In [45]:
df.head(3)

    index  apples  oranges
0    June       3        0
1  Robert       2        3
2    Lily       0        7

In [46]:
df.head()

    index  apples  oranges
0    June       3        0
1  Robert       2        3
2    Lily       0        7
3   David       1        2

In [47]:
df.tail()

    index  apples  oranges
0    June       3        0
1  Robert       2        3
2    Lily       0        7
3   David       1        2

In [48]:
df.tail(1)

   index  apples  oranges
3  David       1        2

In [50]:
MoviesData = pd.read_csv("IMDB-Movie-Data.csv")

In [51]:
MoviesData.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [52]:
MoviesData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [53]:
MoviesData.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000